export type EmailTemplateKey =
  | 'DEMO_SUBMISSION_RECEIVED'
  | 'CONTACT_CONFIRMATION'
  | 'CUSTOM_COMMUNICATION'
  | 'WITHDRAWAL_PAID'
  | 'WITHDRAWAL_REJECTED'
  | 'WITHDRAWAL_APPROVED'
  | 'WITHDRAWAL_RECEIVED'
  | 'MUSIC_LINK_PUBLISHED'
  | 'RELEASE_PUBLISHED'
  | 'EMAIL_VERIFICATION'
  | 'ADMIN_INVITE'
  | 'PASSWORD_RESET'
  | 'ARTIST_INVITATION'
  | 'ARTIST_WELCOME'
  | 'AGREEMENT_SIGNED'
  | 'ARTIST_AGREEMENT'
  | 'VERIFY_EMAIL'
  | 'DEMO_ACCEPTED';

export interface EmailTemplateConfig {
  id: string;
  alias: string;
  name: string;
  defaultSubject: string;
  vars: string[];
}

export const EMAIL_TEMPLATES: Record<EmailTemplateKey, EmailTemplateConfig> = {
  DEMO_SUBMISSION_RECEIVED: {
    id: '17bc854f-b0ed-475e-9c6c-bc8ec1fbee14',
    alias: 'demosubmissionreceived',
    name: 'DemoSubmissionReceived',
    defaultSubject: 'Demo Submission Received - CHENAB MEDIA A&R',
    vars: [
      'logoUrl',
      'artistName',
      'demoId',
      'trackTitle',
      'genre',
      'submittedAt',
      'estimatedReviewTime',
      'website',
      'supportEmail',
      'supportPhone',
      'year',
      'companyName',
    ],
  },
  CONTACT_CONFIRMATION: {
    id: 'cd53fea0-68bb-4019-9d24-804fad6407a0',
    alias: 'contactconfirmation',
    name: 'ContactConfirmation',
    defaultSubject: 'Message Received - CHENAB MEDIA Correspondence',
    vars: [
      'logoUrl',
      'contactName',
      'ticketId',
      'subject',
      'submittedAt',
      'expectedResponse',
      'website',
      'supportEmail',
      'supportPhone',
      'year',
      'companyName',
    ],
  },
  CUSTOM_COMMUNICATION: {
    id: '9078d2b7-9f86-4105-8c6c-6180e260a322',
    alias: 'customcommunication',
    name: 'CustomCommunication',
    defaultSubject: 'Official Notice - CHENAB MEDIA',
    vars: [
      'emailSubject',
      'logoUrl',
      'emailCategory',
      'heading',
      'subheading',
      'recipientName',
      'message',
      'buttonUrl',
      'buttonText',
      'secondaryButtonUrl',
      'secondaryButtonText',
      'signatureName',
      'signatureRole',
      'signatureDepartment',
      'senderEmail',
      'signaturePhone',
      'signatureWebsite',
      'footerText',
      'socialInstagram',
      'socialSpotify',
      'socialYouTube',
      'socialX',
      'socialFacebook',
      'website',
      'supportEmail',
      'supportPhone',
      'year',
      'companyName',
    ],
  },
  WITHDRAWAL_PAID: {
    id: '07f8a34b-4438-4777-ad46-5d85ee59a9f1',
    alias: 'withdrawalpaid',
    name: 'WithdrawalPaid',
    defaultSubject: 'Withdrawal Processed & Paid - CHENAB MEDIA Finance',
    vars: [
      'logoUrl',
      'artistName',
      'withdrawalId',
      'withdrawalAmount',
      'withdrawalCurrency',
      'paymentMethod',
      'paymentDate',
      'transactionReference',
      'paymentStatus',
      'dashboardLink',
      'paymentReceiptUrl',
      'invoiceUrl',
      'website',
      'supportEmail',
      'supportPhone',
      'year',
      'companyName',
    ],
  },
  WITHDRAWAL_REJECTED: {
    id: '180e3f12-5560-4d8d-a6b6-ef3ced5c57f7',
    alias: 'withdrawalrejected',
    name: 'WithdrawalRejected',
    defaultSubject: 'Withdrawal Request Update - CHENAB MEDIA Finance',
    vars: [
      'logoUrl',
      'artistName',
      'withdrawalId',
      'withdrawalAmount',
      'withdrawalCurrency',
      'withdrawalMethod',
      'withdrawalStatus',
      'rejectedDate',
      'rejectionReason',
      'adminNotes',
      'dashboardLink',
      'website',
      'supportEmail',
      'supportPhone',
      'year',
      'companyName',
    ],
  },
  WITHDRAWAL_APPROVED: {
    id: 'd99e2043-518b-4b92-9d4b-1b1b35dbf7b1',
    alias: 'withdrawalapproved',
    name: 'WithdrawalApproved',
    defaultSubject: 'Withdrawal Request Approved - CHENAB MEDIA Finance',
    vars: [
      'logoUrl',
      'artistName',
      'withdrawalId',
      'withdrawalAmount',
      'withdrawalCurrency',
      'withdrawalMethod',
      'withdrawalStatus',
      'approvedDate',
      'estimatedPaymentDate',
      'financeReference',
      'dashboardLink',
      'website',
      'supportEmail',
      'supportPhone',
      'year',
      'companyName',
    ],
  },
  WITHDRAWAL_RECEIVED: {
    id: '95f493cb-44bf-48a2-9fd3-d1055d095749',
    alias: 'withdrawalreceived',
    name: 'WithdrawalReceived',
    defaultSubject: 'Withdrawal Request Logged - CHENAB MEDIA Finance',
    vars: [
      'logoUrl',
      'artistName',
      'withdrawalId',
      'withdrawalAmount',
      'withdrawalCurrency',
      'withdrawalMethod',
      'withdrawalStatus',
      'requestDate',
      'estimatedProcessingTime',
      'dashboardLink',
      'website',
      'supportEmail',
      'supportPhone',
      'year',
      'companyName',
    ],
  },
  MUSIC_LINK_PUBLISHED: {
    id: 'a6f0022e-6e3f-4463-ae78-d7a5714e339e',
    alias: 'musiclinkpublished',
    name: 'MusicLinkPublished',
    defaultSubject: 'SmartLink Live & Ready - CHENAB MEDIA Catalogue',
    vars: [
      'logoUrl',
      'releaseTitle',
      'coverArtwork',
      'artistName',
      'smartLink',
      'qrCodeUrl',
      'website',
      'supportEmail',
      'year',
      'companyName',
    ],
  },
  RELEASE_PUBLISHED: {
    id: '79398eb7-a389-4d7e-bc4a-4d1a71dd72e1',
    alias: 'releasepublished',
    name: 'ReleasePublished',
    defaultSubject: 'Catalogue Release Published - CHENAB MEDIA Distribution',
    vars: [
      'logoUrl',
      'releaseTitle',
      'coverArtwork',
      'artistName',
      'releaseType',
      'smartLink',
      'spotifyLink',
      'appleMusicLink',
      'youtubeLink',
      'youtubeMusicLink',
      'amazonMusicLink',
      'soundCloudLink',
      'audiomackLink',
      'website',
      'supportEmail',
      'year',
      'companyName',
    ],
  },
  EMAIL_VERIFICATION: {
    id: '9379c2da-0c0b-4fe0-90f7-277d01a24b7b',
    alias: 'emailverification',
    name: 'EmailVerification',
    defaultSubject: 'Verify Your Email Address - CHENAB MEDIA Portal',
    vars: [
      'logoUrl',
      'userName',
      'userEmail',
      'userRole',
      'verificationExpiry',
      'verificationLink',
      'verificationCode',
      'supportEmail',
      'supportPhone',
      'website',
      'year',
      'companyName',
    ],
  },
  ADMIN_INVITE: {
    id: 'f4ea7f2a-84bd-4f80-af46-4bedce6b98b8',
    alias: 'admininvite',
    name: 'AdminInvite',
    defaultSubject: 'Administrative Access Provisioned - CHENAB MEDIA Portal',
    vars: [
      'logoUrl',
      'adminName',
      'invitedBy',
      'adminRole',
      'adminEmail',
      'invitationId',
      'invitationExpiry',
      'acceptInvitationLink',
      'supportEmail',
      'supportPhone',
      'website',
      'year',
      'companyName',
    ],
  },
  PASSWORD_RESET: {
    id: '12fe0f11-296c-4173-aa1f-9d3e4e82dd55',
    alias: 'passwordreset',
    name: 'PasswordReset',
    defaultSubject: 'Password Reset Request - CHENAB MEDIA Account',
    vars: [
      'logoUrl',
      'userName',
      'userRole',
      'userEmail',
      'requestTime',
      'requestDevice',
      'requestBrowser',
      'requestIp',
      'resetPasswordLink',
      'supportEmail',
      'supportPhone',
      'website',
      'year',
      'companyName',
    ],
  },
  ARTIST_INVITATION: {
    id: '872278df-8528-45f5-be02-afbe4fd9800a',
    alias: 'artistinvitation',
    name: 'ArtistInvitation',
    defaultSubject: 'Invitation to Join CHENAB MEDIA Roster',
    vars: [
      'logoUrl',
      'artistStageName',
      'invitedBy',
      'labelName',
      'artistRole',
      'invitationId',
      'invitationExpiry',
      'acceptInvitationLink',
      'supportEmail',
      'supportPhone',
      'website',
      'year',
      'companyName',
    ],
  },
  ARTIST_WELCOME: {
    id: 'ad41837f-5bb2-40ec-9b7f-571ec2cae494',
    alias: 'artistwelcome',
    name: 'ArtistWelcome',
    defaultSubject: 'Welcome to CHENAB MEDIA Roster',
    vars: [
      'logoUrl',
      'artistStageName',
      'artistId',
      'artistEmail',
      'temporaryPassword',
      'loginLink',
      'supportEmail',
      'supportPhone',
      'website',
      'year',
      'companyName',
    ],
  },
  AGREEMENT_SIGNED: {
    id: '970b10b1-126f-4470-ac03-f583d8824711',
    alias: 'agreementsigned',
    name: 'AgreementSigned',
    defaultSubject: 'Agreement Signed & Executed - CHENAB MEDIA Legal',
    vars: [
      'logoUrl',
      'artistName',
      'agreementId',
      'agreementTitle',
      'agreementStatus',
      'signedDate',
      'effectiveDate',
      'agreementDownloadLink',
      'verificationLink',
      'googleDriveLink',
      'supportEmail',
      'supportPhone',
      'website',
      'year',
      'companyName',
    ],
  },
  ARTIST_AGREEMENT: {
    id: '71cf2279-5742-4914-95e0-3ab2d5b87b3c',
    alias: 'artistagreement',
    name: 'ArtistAgreement',
    defaultSubject: 'New Agreement Issued - CHENAB MEDIA Legal',
    vars: [
      'artistName',
      'labelName',
      'contractType',
      'agreementTitle',
      'agreementId',
      'expiryDate',
      'signingLink',
      'supportEmail',
    ],
  },
  VERIFY_EMAIL: {
    id: 'd277e5db-37b0-4eb6-9eb2-c5e9434264f0',
    alias: 'verifyemail',
    name: 'VerifyEmail',
    defaultSubject: 'Please Verify Your Email Address',
    vars: ['name', 'verificationUrl'],
  },
  DEMO_ACCEPTED: {
    id: '21284f72-6e99-440b-a10e-2b2dd7caeba0',
    alias: 'resend_template_demo_accepted',
    name: 'DemoAccepted',
    defaultSubject: 'Demo Accepted - CHENAB MEDIA A&R',
    vars: [
      'logoUrl',
      'artistName',
      'demoId',
      'trackTitle',
      'genre',
      'reviewDate',
      'reviewerName',
      'nextSteps',
      'meetingLink',
      'supportEmail',
      'supportPhone',
      'website',
      'year',
      'companyName',
    ],
  },
};

export const DEFAULT_GLOBAL_VARS = {
  logoUrl: 'https://chenabmedia.in/logo.png',
  website: 'https://chenabmedia.in',
  supportEmail: 'admin@chenabmedia.in',
  supportPhone: '+1 (800) 555-CHENAB',
  companyName: 'Chenab Media',
  year: new Date().getFullYear().toString(),
};
