export const EMAIL_TEMPLATES = {
  DEMO_SUBMISSION_RECEIVED: 'DemoSubmissionReceived',
  CONTACT_CONFIRMATION: 'ContactConfirmation',
  CUSTOM_COMMUNICATION: 'CustomCommunication',
  WITHDRAWAL_PAID: 'WithdrawalPaid',
  WITHDRAWAL_REJECTED: 'WithdrawalRejected',
  WITHDRAWAL_APPROVED: 'WithdrawalApproved',
  WITHDRAWAL_RECEIVED: 'WithdrawalReceived',
  MUSIC_LINK_PUBLISHED: 'MusicLinkPublished',
  RELEASE_PUBLISHED: 'ReleasePublished',
  EMAIL_VERIFICATION: 'EmailVerification',
  ADMIN_INVITE: 'AdminInvite',
  PASSWORD_RESET: 'PasswordReset',
  ARTIST_INVITATION: 'ArtistInvitation',
  ARTIST_WELCOME: 'ArtistWelcome',
  AGREEMENT_SIGNED: 'AgreementSigned',
  ARTIST_AGREEMENT: 'ArtistAgreement',
  VERIFY_EMAIL: 'VerifyEmail',
} as const;

export type EmailTemplateKey = keyof typeof EMAIL_TEMPLATES;

export interface EmailTemplateConfig {
  id: string;
  alias: string;
  name: string;
  defaultSubject: string;
  vars: string[];
}

export const EMAIL_TEMPLATE_CONFIGS: Record<EmailTemplateKey, EmailTemplateConfig> = {
  DEMO_SUBMISSION_RECEIVED: {
    id: EMAIL_TEMPLATES.DEMO_SUBMISSION_RECEIVED,
    alias: 'demosubmissionreceived',
    name: EMAIL_TEMPLATES.DEMO_SUBMISSION_RECEIVED,
    defaultSubject: 'Demo Submission Received - CHENAB MEDIA A&R',
    vars: [
      'logoUrl',
      'artistName',
      'demoId',
      'trackTitle',
      'genre',
      'submittedAt',
      'estimatedReviewTime',
      'website',
      'supportEmail',
      'supportPhone',
      'year',
      'companyName',
    ],
  },
  CONTACT_CONFIRMATION: {
    id: EMAIL_TEMPLATES.CONTACT_CONFIRMATION,
    alias: 'contactconfirmation',
    name: EMAIL_TEMPLATES.CONTACT_CONFIRMATION,
    defaultSubject: 'Message Received - CHENAB MEDIA Correspondence',
    vars: [
      'logoUrl',
      'contactName',
      'ticketId',
      'subject',
      'submittedAt',
      'expectedResponse',
      'website',
      'supportEmail',
      'supportPhone',
      'year',
      'companyName',
    ],
  },
  CUSTOM_COMMUNICATION: {
    id: EMAIL_TEMPLATES.CUSTOM_COMMUNICATION,
    alias: 'customcommunication',
    name: EMAIL_TEMPLATES.CUSTOM_COMMUNICATION,
    defaultSubject: 'Official Notice - CHENAB MEDIA',
    vars: [
      'emailSubject',
      'logoUrl',
      'emailCategory',
      'heading',
      'subheading',
      'recipientName',
      'message',
      'buttonUrl',
      'buttonText',
      'secondaryButtonUrl',
      'secondaryButtonText',
      'signatureName',
      'signatureRole',
      'signatureDepartment',
      'senderEmail',
      'signaturePhone',
      'signatureWebsite',
      'footerText',
      'socialInstagram',
      'socialSpotify',
      'socialYouTube',
      'socialX',
      'socialFacebook',
      'website',
      'supportEmail',
      'supportPhone',
      'year',
      'companyName',
    ],
  },
  WITHDRAWAL_PAID: {
    id: EMAIL_TEMPLATES.WITHDRAWAL_PAID,
    alias: 'withdrawalpaid',
    name: EMAIL_TEMPLATES.WITHDRAWAL_PAID,
    defaultSubject: 'Withdrawal Processed & Paid - CHENAB MEDIA Finance',
    vars: [
      'logoUrl',
      'artistName',
      'withdrawalId',
      'withdrawalAmount',
      'withdrawalCurrency',
      'paymentMethod',
      'paymentDate',
      'transactionReference',
      'paymentStatus',
      'dashboardLink',
      'paymentReceiptUrl',
      'invoiceUrl',
      'website',
      'supportEmail',
      'supportPhone',
      'year',
      'companyName',
    ],
  },
  WITHDRAWAL_REJECTED: {
    id: EMAIL_TEMPLATES.WITHDRAWAL_REJECTED,
    alias: 'withdrawalrejected',
    name: EMAIL_TEMPLATES.WITHDRAWAL_REJECTED,
    defaultSubject: 'Withdrawal Request Update - CHENAB MEDIA Finance',
    vars: [
      'logoUrl',
      'artistName',
      'withdrawalId',
      'withdrawalAmount',
      'withdrawalCurrency',
      'withdrawalMethod',
      'withdrawalStatus',
      'rejectedDate',
      'rejectionReason',
      'adminNotes',
      'dashboardLink',
      'website',
      'supportEmail',
      'supportPhone',
      'year',
      'companyName',
    ],
  },
  WITHDRAWAL_APPROVED: {
    id: EMAIL_TEMPLATES.WITHDRAWAL_APPROVED,
    alias: 'withdrawalapproved',
    name: EMAIL_TEMPLATES.WITHDRAWAL_APPROVED,
    defaultSubject: 'Withdrawal Request Approved - CHENAB MEDIA Finance',
    vars: [
      'logoUrl',
      'artistName',
      'withdrawalId',
      'withdrawalAmount',
      'withdrawalCurrency',
      'withdrawalMethod',
      'withdrawalStatus',
      'approvedDate',
      'estimatedPaymentDate',
      'financeReference',
      'dashboardLink',
      'website',
      'supportEmail',
      'supportPhone',
      'year',
      'companyName',
    ],
  },
  WITHDRAWAL_RECEIVED: {
    id: EMAIL_TEMPLATES.WITHDRAWAL_RECEIVED,
    alias: 'withdrawalreceived',
    name: EMAIL_TEMPLATES.WITHDRAWAL_RECEIVED,
    defaultSubject: 'Withdrawal Request Logged - CHENAB MEDIA Finance',
    vars: [
      'logoUrl',
      'artistName',
      'withdrawalId',
      'withdrawalAmount',
      'withdrawalCurrency',
      'withdrawalMethod',
      'withdrawalStatus',
      'requestDate',
      'estimatedProcessingTime',
      'dashboardLink',
      'website',
      'supportEmail',
      'supportPhone',
      'year',
      'companyName',
    ],
  },
  MUSIC_LINK_PUBLISHED: {
    id: EMAIL_TEMPLATES.MUSIC_LINK_PUBLISHED,
    alias: 'musiclinkpublished',
    name: EMAIL_TEMPLATES.MUSIC_LINK_PUBLISHED,
    defaultSubject: 'SmartLink Live & Ready - CHENAB MEDIA Catalogue',
    vars: [
      'logoUrl',
      'releaseTitle',
      'coverArtwork',
      'artistName',
      'smartLink',
      'qrCodeUrl',
      'website',
      'supportEmail',
      'year',
      'companyName',
    ],
  },
  RELEASE_PUBLISHED: {
    id: EMAIL_TEMPLATES.RELEASE_PUBLISHED,
    alias: 'releasepublished',
    name: EMAIL_TEMPLATES.RELEASE_PUBLISHED,
    defaultSubject: 'Catalogue Release Published - CHENAB MEDIA Distribution',
    vars: [
      'logoUrl',
      'releaseTitle',
      'coverArtwork',
      'artistName',
      'releaseType',
      'smartLink',
      'spotifyLink',
      'appleMusicLink',
      'youtubeLink',
      'youtubeMusicLink',
      'amazonMusicLink',
      'soundCloudLink',
      'audiomackLink',
      'website',
      'supportEmail',
      'year',
      'companyName',
    ],
  },
  EMAIL_VERIFICATION: {
    id: EMAIL_TEMPLATES.EMAIL_VERIFICATION,
    alias: 'emailverification',
    name: EMAIL_TEMPLATES.EMAIL_VERIFICATION,
    defaultSubject: 'Verify Your Email Address - CHENAB MEDIA Portal',
    vars: [
      'logoUrl',
      'userName',
      'userEmail',
      'userRole',
      'verificationExpiry',
      'verificationLink',
      'verificationCode',
      'supportEmail',
      'supportPhone',
      'website',
      'year',
      'companyName',
    ],
  },
  ADMIN_INVITE: {
    id: EMAIL_TEMPLATES.ADMIN_INVITE,
    alias: 'admininvite',
    name: EMAIL_TEMPLATES.ADMIN_INVITE,
    defaultSubject: 'Administrative Access Provisioned - CHENAB MEDIA Portal',
    vars: [
      'logoUrl',
      'adminName',
      'invitedBy',
      'adminRole',
      'adminEmail',
      'invitationId',
      'invitationExpiry',
      'acceptInvitationLink',
      'supportEmail',
      'supportPhone',
      'website',
      'year',
      'companyName',
    ],
  },
  PASSWORD_RESET: {
    id: EMAIL_TEMPLATES.PASSWORD_RESET,
    alias: 'passwordreset',
    name: EMAIL_TEMPLATES.PASSWORD_RESET,
    defaultSubject: 'Password Reset Request - CHENAB MEDIA Account',
    vars: [
      'logoUrl',
      'userName',
      'userRole',
      'userEmail',
      'requestTime',
      'requestDevice',
      'requestBrowser',
      'requestIp',
      'resetPasswordLink',
      'supportEmail',
      'supportPhone',
      'website',
      'year',
      'companyName',
    ],
  },
  ARTIST_INVITATION: {
    id: EMAIL_TEMPLATES.ARTIST_INVITATION,
    alias: 'artistinvitation',
    name: EMAIL_TEMPLATES.ARTIST_INVITATION,
    defaultSubject: 'Invitation to Join CHENAB MEDIA Roster',
    vars: [
      'logoUrl',
      'artistStageName',
      'invitedBy',
      'labelName',
      'artistRole',
      'invitationId',
      'invitationExpiry',
      'acceptInvitationLink',
      'supportEmail',
      'supportPhone',
      'website',
      'year',
      'companyName',
    ],
  },
  ARTIST_WELCOME: {
    id: EMAIL_TEMPLATES.ARTIST_WELCOME,
    alias: 'artistwelcome',
    name: EMAIL_TEMPLATES.ARTIST_WELCOME,
    defaultSubject: 'Welcome to CHENAB MEDIA Roster',
    vars: [
      'logoUrl',
      'artistStageName',
      'artistId',
      'artistEmail',
      'temporaryPassword',
      'loginLink',
      'supportEmail',
      'supportPhone',
      'website',
      'year',
      'companyName',
    ],
  },
  AGREEMENT_SIGNED: {
    id: EMAIL_TEMPLATES.AGREEMENT_SIGNED,
    alias: 'agreementsigned',
    name: EMAIL_TEMPLATES.AGREEMENT_SIGNED,
    defaultSubject: 'Agreement Signed & Executed - CHENAB MEDIA Legal',
    vars: [
      'logoUrl',
      'artistName',
      'agreementId',
      'agreementTitle',
      'agreementStatus',
      'signedDate',
      'effectiveDate',
      'agreementDownloadLink',
      'verificationLink',
      'googleDriveLink',
      'supportEmail',
      'supportPhone',
      'website',
      'year',
      'companyName',
    ],
  },
  ARTIST_AGREEMENT: {
    id: EMAIL_TEMPLATES.ARTIST_AGREEMENT,
    alias: 'artistagreement',
    name: EMAIL_TEMPLATES.ARTIST_AGREEMENT,
    defaultSubject: 'New Agreement Issued - CHENAB MEDIA Legal',
    vars: [
      'artistName',
      'labelName',
      'contractType',
      'agreementTitle',
      'agreementId',
      'expiryDate',
      'signingLink',
      'supportEmail',
    ],
  },
  VERIFY_EMAIL: {
    id: EMAIL_TEMPLATES.VERIFY_EMAIL,
    alias: 'verifyemail',
    name: EMAIL_TEMPLATES.VERIFY_EMAIL,
    defaultSubject: 'Please Verify Your Email Address',
    vars: ['name', 'verificationUrl'],
  },
};

export const DEFAULT_GLOBAL_VARS = {
  logoUrl: 'https://chenabmedia.in/logo.png',
  website: 'https://chenabmedia.in',
  supportEmail: 'admin@chenabmedia.in',
  supportPhone: '+1 (800) 555-CHENAB',
  companyName: 'Chenab Media',
  labelName: 'CHENAB MEDIA',
  year: new Date().getFullYear().toString(),
};
